include:
  - 'modules/**/.gitlab-ci.yml'

.build:
  stage: build
  image:
    name: registry.gitlab.rlp.net/imbforge/imb-cicd/buildah:latest
  variables:
    STORAGE_DRIVER: vfs
  before_script:
    - echo ${CI_REGISTRY_PASSWORD} | buildah login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
  script:
    - buildah bud --tag ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}:${CI_COMMIT_BRANCH:-${CI_COMMIT_TAG}} modules/${CI_JOB_NAME}
    - buildah push --authfile /run/containers/0/auth.json ${CI_REGISTRY_IMAGE}/${CI_JOB_NAME}:${CI_COMMIT_BRANCH:-${CI_COMMIT_TAG}}
  after_script:
    - buildah logout ${CI_REGISTRY}
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
      changes:
        paths:
          - 'modules/${CI_JOB_NAME}/Dockerfile'
          - 'modules/${CI_JOB_NAME}/pixi.*'
