[project]
name = "fold2go"
version = "0.1.0"
description = "Nextflow wrapper for alphafold2"
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]
setup = "pip install -r .jupyter/requirements.txt"
imb-alphafold = { cmd = "jupyterhub --config .jupyter/jupyterhub_config.py", depends_on = ["setup"] }

[dependencies]
jupyterhub = ">=5.0.0,<5.1"
nextflow = ">=24.4.1,<24.5"
pip = ">=24.0,<25"
python-ldap = ">=3.4.3,<3.5"
