[workspace]
name = "colabfold"
version = "1.6.1"
description = "Add a short description here"
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge","bioconda"]
platforms = [{ platform = "linux-64", cuda = "12.0" }]

[dependencies]
python = "3.13.*"
kalign2 = "==2.04"
hhsuite = "==3.3.0"
mmseqs2 = "==18.8cc5c"
entrez-direct = ">=24.0,<25"
seqkit = ">=2.13.0,<3"

[pypi-dependencies]
colabfold = { version = "==1.6.2", extras = ["alphafold", "openmm"] }
jax = { extras = ["cuda12"] }
openmm = { extras = ["cuda12"] }
