[workspace]
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "boltz"
platforms = [{ platform = "linux-64", cuda = "12.0" }]
version = "0.1.0"

[dependencies]
python = "3.12.*"

[pypi-dependencies]
boltz = { version = "==2.2.1", extras = ["cuda"] }
