[project]
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "boltz"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
boltz = { git = "https://github.com/jwohlwend/boltz", rev = "e3b5e1da6c9e3954ab4e3fb92563707c8961d3af" }
