[project]
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "boltz"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
boltz = { git = "https://github.com/jwohlwend/boltz", rev = "a062087d3a61a479e9eb6e6ce651156fb2ec38a9" }
