[project]
name = "shiny"
version = "0.1.0"
description = "Add a short description here"
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
plotly = ">=6.3.0,<7"
polars = ">=1.33.1,<2"

[pypi-dependencies]
ipymolstar = { git = "https://github.com/molstar/ipymolstar", tag = "v0.1.0" }
shiny = "==1.5.0"
shinywidgets = "==0.7.0"


