[workspace]
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "alphafold"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.6.3"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
alphafold3 = { git = "https://github.com/google-deepmind/alphafold3", rev = "87bd9e678d9acacc4aa9baa05e820f32b80e1b49" }
