[project]
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "alphafold"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.6"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
alphafold3 = { git = "https://github.com/google-deepmind/alphafold3", rev = "792e61e099ae011ab9d8f55768adbb95e08343b9" }
absl-py = "==2.1.0"
chex = "==0.1.87"
dm-haiku = "==0.0.13"
dm-tree = "==0.1.8"
filelock = "==3.16.1"
jax = { version = "==0.4.34", extras = ["cuda12"] }
jax-cuda12-pjrt = "==0.4.34"
jax-cuda12-plugin = { version = "==0.4.34", extras = ["with-cuda"] }
jax-triton = "==0.2.0"
jaxlib = "==0.4.34"
jaxtyping = "==0.2.34"
jmp = "==0.0.4"
ml-dtypes = "==0.5.0"
numpy = "==2.1.3"
nvidia-cublas-cu12 = "==12.6.3.3"
nvidia-cuda-cupti-cu12 = "==12.6.80"
nvidia-cuda-nvcc-cu12 = "==12.6.77"
nvidia-cuda-runtime-cu12 = "==12.6.77"
nvidia-cudnn-cu12 = "==9.5.1.17"
nvidia-cufft-cu12 = "==11.3.0.4"
nvidia-cusolver-cu12 = "==11.7.1.2"
nvidia-cusparse-cu12 = "==12.5.4.2"
nvidia-nccl-cu12 = "==2.23.4"
nvidia-nvjitlink-cu12 = "==12.6.77"
opt-einsum = "==3.4.0"
pillow = "==11.0.0"
rdkit = "==2024.3.5"
scipy = "==1.14.1"
tabulate = "==0.9.0"
toolz = "==1.0.0"
tqdm = "==4.67.0"
triton = "==3.1.0"
typeguard = "==2.13.3"
typing-extensions = "==4.12.2"
zstandard = "==0.23.0"
