[project]
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "alphafold"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12"

[tasks]

[dependencies]
python = "3.12.*"
hmmer = ">=3.4,<4"
setuptools = ">=75.5.0,<76"
zstd = ">=1.5.6,<2"

[pypi-dependencies]
alphafold3 = { git = "https://github.com/google-deepmind/alphafold3", rev = "7f6edd04a4aeffa65d349d51b1ca81cfd34549af" }
