[project]
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "alphafold"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.5"

[tasks]

[dependencies]
python = "3.11.*"
hmmer = ">=3.4,<4"
setuptools = ">=75.5.0,<76"
zstd = ">=1.5.6,<2"

[pypi-dependencies]
alphafold3 = { git = "https://github.com/google-deepmind/alphafold3", rev = "1558f06eb3a38921015c815dde0580782caa54f2" }
