[project]
name = "pymol"
version = "0.1.0"
description = "Add a short description here"
authors = ["Patrick Hüther <huether@imb-mainz.de>"]
channels = ["conda-forge","schrodinger"]
platforms = ["linux-64"]

[tasks]

[dependencies]
pymol-bundle = ">=2.4.1,<2.5"
mdtraj = ">=1.10.0,<1.11"
